//#define JADE_ADMIN_Z_LEVEL 8
//#define JADE_MAX_MAP_Z_LEVEL 7
#define JADE_MIN_MAP_Z_LEVEL 1
#define ZLEVEL_ALL -1

#define SILKTREE_HARDCAP 30

#define DRUNK_LEVEL_HAPPY 10
#define DRUNK_LEVEL_TIPSY 25